# Generated by Django 5.2 on 2025-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('manager', 'Manager'), ('supervisor', 'Supervisor')], default='viewer', max_length=10),
        ),
    ]
