# Generated by Django 5.2 on 2025-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
