# Generated by Django 5.1.5 on 2025-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_nin_staffattendance_date_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/staff'),
        ),
    ]
