# Generated by Django 5.2 on 2025-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
    ]
