# Generated by Django 3.2.25 on 2025-01-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='special_notes',
            field=models.CharField(blank=True, choices=[('strongly spiced', 'Dine-In'), ('midly spiced', 'Take-Away'), ('chips', 'chips'), ('rice', 'rice'), ('posho', 'posho'), ('rice_posho', 'rice_posho'), ('chips_rice', 'chips_rice'), ('rice_posho', 'rice_posho'), ('chips_posho', 'chips_posho')], default='nothing', max_length=50, null=True),
        ),
    ]
