# Generated by Django 5.1.5 on 2025-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_orderitem_options_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-order_date'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='special_notes',
            field=models.CharField(blank=True, choices=[('strongly spiced', 'strongly spiced'), ('midly spiced', 'midly spiced'), ('chips', 'chips'), ('rice', 'rice'), ('posho', 'posho'), ('rice_posho', 'rice_posho'), ('chips_rice', 'chips_rice'), ('rice_posho', 'rice_posho'), ('chips_posho', 'chips_posho')], default='nothing', max_length=50, null=True),
        ),
    ]
