# Generated by Django 5.1.5 on 2025-03-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomreservation',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='HotelBranch',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
