# Generated by Django 5.2 on 2025-04-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_roomreservation_customer_remove_room_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='customer_name',
            field=models.CharField(blank=True, default='Customer', max_length=255, null=True),
        ),
    ]
