# Generated by Django 5.2 on 2025-04-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_orderitem_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='customer_name',
            field=models.CharField(blank=True, default='Customer', max_length=255, null=True),
        ),
    ]
