# Generated by Django 5.2 on 2025-05-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_orderitem_special_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
