# Generated by Django 5.2 on 2025-05-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_orderitem_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
