# Generated by Django 5.1.5 on 2025-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_expense_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='drawn_by',
            field=models.CharField(default='staff', max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
