# Generated by Django 5.1.5 on 2025-05-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='description',
            field=models.TextField(default='revenue', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='received_from',
            field=models.CharField(default='staff', max_length=30),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='category',
            field=models.CharField(choices=[('rooms', 'Rooms'), ('fnb', 'Food & Beverage'), ('party', 'Party'), ('other', 'Other')], max_length=20),
        ),
    ]
