# Generated by Django 5.1.5 on 2025-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_revenue_description_revenue_received_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_acquired', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('staff', 'Salaries and Wages'), ('utilities', 'Utilities'), ('repairs', 'Repairs and Maintenance'), ('supplies', 'Cleaning & Room Supplies'), ('fnb', 'Food and Beverage'), ('admin', 'Administrative'), ('marketing', 'Sales and Marketing'), ('finance', 'Finance Costs'), ('depreciation', 'Depreciation'), ('other', 'Other')], max_length=30),
        ),
    ]
