# Generated by Django 5.1.5 on 2025-05-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_asset_liability_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default='office', max_length=100),
            preserve_default=False,
        ),
    ]
