# Generated by Django 5.1.5 on 2025-05-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_asset_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Liability',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
