# Generated by Django 5.2 on 2025-05-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_delete_asset_delete_expense_delete_liability_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name']},
        ),
    ]
