# Generated by Django 5.1.5 on 2025-06-02 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_menuitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='served_by',
            field=models.CharField(blank=True, default='Waitress', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
