# Generated by Django 5.1.5 on 2025-07-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_ordertransaction_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='payment_mode',
            field=models.CharField(choices=[('NO PAYMENT', 'NO PAYMENT'), ('CASH', 'CASH'), ('MOMO PAY', 'MOMO PAY'), ('AIRTEL PAY', 'AIRTEL PAY'), ('INVOICE', 'INVOICE'), ('ON ACCOMMODATION', 'ON ACCOMMODATION')], default='NO PAYMENT', max_length=50),
        ),
    ]
