# Generated by Django 5.1.5 on 2025-07-14 19:18

import django.db.models.deletion
import django.utils.timezone
import room_bookings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('NIN', models.CharField(default='', max_length=100)),
                ('customerid_image', models.ImageField(blank=True, null=True, upload_to='rooms')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Sauna_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('price_per_night', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='rooms')),
                ('floor', models.IntegerField()),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room_bookings.hotelbranch')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room_bookings.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('reserved', 'Converted to Reservation'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_bookings.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.BigIntegerField(default=0, editable=False, unique=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('NIN', models.CharField(default='', max_length=100)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('reservation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out')], default='Pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='room_bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='room_bookings.room')),
            ],
        ),
        migrations.CreateModel(
            name='SaunaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(default=room_bookings.models.generate_random_id, editable=False, max_length=6, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('keys', models.CharField(choices=[('key_001', 'key_001'), ('key_002', 'key_002'), ('key_003', 'key_003'), ('key_004', 'key_004'), ('key_005', 'key_005'), ('key_006', 'key_006'), ('key_007', 'key_007'), ('key_008', 'key_008'), ('key_009', 'key_009'), ('key_010', 'key_010'), ('key_011', 'key_011'), ('key_012', 'key_012'), ('key_013', 'key_013'), ('key_014', 'key_014'), ('key_015', 'key_015'), ('key_016', 'key_016')], max_length=100)),
                ('price', models.IntegerField(blank=True, editable=False, null=True)),
                ('payment_mode', models.CharField(choices=[('NO PAYMENT', 'NO PAYMENT'), ('CASH', 'CASH'), ('MOMO PAY', 'MOMO PAY'), ('AIRTEL PAY', 'AIRTEL PAY'), ('ON_ACCOMMODATION', 'ON ACCOMMODATION')], default='NO PAYMENT', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID / Invoice Number', max_length=100, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_bookings.sauna_services')),
            ],
        ),
    ]
