# Generated by Django 5.2 on 2025-04-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='NIN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='roomreservation',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
