# Generated by Django 5.1.5 on 2025-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saunauser',
            name='payment_mode',
            field=models.CharField(choices=[('NO PAYMENT', 'NO PAYMENT'), ('CASH', 'CASH'), ('MOMO PAY', 'MOMO PAY'), ('AIRTEL PAY', 'AIRTEL PAY'), ('ON ACCOMMODATION', 'ON ACCOMMODATION')], default='NO PAYMENT', max_length=20),
        ),
    ]
