# Generated by Django 5.1.5 on 2025-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0002_alter_saunauser_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saunauser',
            name='keys',
            field=models.CharField(choices=[('no_key', 'No Key'), ('reception', 'Left at Reception'), ('key_001', 'key_001'), ('key_002', 'key_002'), ('key_003', 'key_003'), ('key_004', 'key_004'), ('key_005', 'key_005'), ('key_006', 'key_006'), ('key_007', 'key_007'), ('key_008', 'key_008'), ('key_009', 'key_009'), ('key_010', 'key_010'), ('key_011', 'key_011'), ('key_012', 'key_012'), ('key_013', 'key_013'), ('key_014', 'key_014'), ('key_015', 'key_015')], max_length=100),
        ),
    ]
