# Generated by Django 5.2 on 2025-04-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0003_alter_room_hotel_alter_roomtype_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
