# Generated by Django 5.1.5 on 2025-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0004_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerid_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
    ]
