# Generated by Django 5.2 on 2025-06-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0005_customer_customerid_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_bookings.room')),
            ],
        ),
    ]
