# Generated by Django 5.2 on 2025-06-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0007_rename_contact_email_booking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
