# Generated by Django 5.1.5 on 2025-06-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0008_booking_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
