# Generated by Django 5.1.5 on 2025-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0009_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reserved', 'Converted to Reservation'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
