# Generated by Django 5.1.5 on 2025-07-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bookings', '0010_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreservation',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='room_bookings.booking'),
        ),
    ]
