# Generated by Django 5.2 on 2025-05-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('Conference', 'Conference Room'), ('Gardens', 'Gardens'), ('Gym', 'Gym Access'), ('Laundry', 'Laundry Service'), ('Massage', 'Massage Therapy'), ('Other', 'Other Service'), ('Parking', 'Car Parking'), ('Pool', 'Swimming Pool'), ('RoomService', 'Room Service'), ('Sauna', 'Sauna Session'), ('Spa', 'Spa Treatment'), ('WiFi', 'High-Speed Wi-Fi')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Additional Service Package',
                'verbose_name_plural': 'Additional Service Packages',
                'ordering': ['-start_time'],
            },
        ),
    ]
