# Generated by Django 5.1.5 on 2025-07-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherPackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpackage',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherpackage',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=2000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otherpackage',
            name='service_type',
            field=models.CharField(choices=[('Conference', 'Conference Room'), ('Gardens', 'Gardens'), ('Gym', 'Gym Access'), ('Laundry', 'Laundry Service'), ('Massage', 'Massage Therapy'), ('Other', 'Other Service'), ('Parking', 'Car Parking'), ('Pool', 'Swimming Pool'), ('RoomService', 'Room Service'), ('Sauna', 'Sauna Session'), ('Spa', 'Spa Treatment'), ('WiFi', 'High-Speed Wi-Fi'), ('Event', 'Event Booking'), ('Birthday', 'Birthday Party')], max_length=50),
        ),
        migrations.AlterField(
            model_name='otherpackage',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
