# Generated by Django 5.1.5 on 2025-07-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherPackages', '0002_otherpackage_amount_paid_otherpackage_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpackage',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
