# Generated by Django 5.1.5 on 2025-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otherPackages', '0006_alter_otherpackage_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpackage',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
